// This file is generated by generateArtifacts.ts. Do not edit it manually.
import type { SymbolMatchPrintedLayouts } from "./types.js";

export const SYMBOL_MATCH_PRINTED_LAYOUTS_VERSION =
  "seeded-circle-packing-v2-noto-roster";
export const SYMBOL_MATCH_PRINTED_LAYOUTS_FINGERPRINT =
  "sha256:3dbe5dce155c179b827224839654fe3d8732781ff84ceb95280df594fc721c63";

export const SYMBOL_MATCH_PRINTED_LAYOUTS = [
  {
    cardId: 0,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.1509,
        y: 0.3787,
        scale: 0.19,
        rotationDegrees: 57.0342
      },
      {
        symbolId: "camera",
        x: 0.8569,
        y: 0.5512,
        scale: 0.22,
        rotationDegrees: 153.282
      },
      {
        symbolId: "cactus",
        x: 0.3647,
        y: 0.8179,
        scale: 0.18,
        rotationDegrees: 209.0492
      },
      {
        symbolId: "frog",
        x: 0.6141,
        y: 0.7406,
        scale: 0.3,
        rotationDegrees: 315.949
      },
      {
        symbolId: "cupcake",
        x: 0.3889,
        y: 0.3454,
        scale: 0.24,
        rotationDegrees: 216.5632
      },
      {
        symbolId: "airplane",
        x: 0.2344,
        y: 0.6127,
        scale: 0.26,
        rotationDegrees: 202.5288
      },
      {
        symbolId: "test-tube",
        x: 0.7264,
        y: 0.3158,
        scale: 0.28,
        rotationDegrees: 219.8301
      },
      {
        symbolId: "heart",
        x: 0.5068,
        y: 0.1316,
        scale: 0.21,
        rotationDegrees: 233.8812
      }
    ]
  },
  {
    cardId: 1,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.3399,
        y: 0.1533,
        scale: 0.18,
        rotationDegrees: 27.7277
      },
      {
        symbolId: "sun",
        x: 0.7468,
        y: 0.6611,
        scale: 0.21,
        rotationDegrees: 32.8264
      },
      {
        symbolId: "snowflake",
        x: 0.3851,
        y: 0.8085,
        scale: 0.26,
        rotationDegrees: 46.7667
      },
      {
        symbolId: "snail",
        x: 0.523,
        y: 0.492,
        scale: 0.3,
        rotationDegrees: 293.3056
      },
      {
        symbolId: "pretzel",
        x: 0.2301,
        y: 0.3689,
        scale: 0.24,
        rotationDegrees: 113.6639
      },
      {
        symbolId: "train",
        x: 0.8184,
        y: 0.3684,
        scale: 0.19,
        rotationDegrees: 103.029
      },
      {
        symbolId: "wand",
        x: 0.1767,
        y: 0.652,
        scale: 0.22,
        rotationDegrees: 246.0755
      },
      {
        symbolId: "heart",
        x: 0.6057,
        y: 0.1862,
        scale: 0.28,
        rotationDegrees: 157.1165
      }
    ]
  },
  {
    cardId: 2,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.5077,
        y: 0.1392,
        scale: 0.22,
        rotationDegrees: 195.5172
      },
      {
        symbolId: "moon",
        x: 0.309,
        y: 0.3536,
        scale: 0.26,
        rotationDegrees: 179.3721
      },
      {
        symbolId: "cat",
        x: 0.8651,
        y: 0.589,
        scale: 0.19,
        rotationDegrees: 153.3711
      },
      {
        symbolId: "bee",
        x: 0.1639,
        y: 0.6135,
        scale: 0.24,
        rotationDegrees: 263.6005
      },
      {
        symbolId: "carrot",
        x: 0.7285,
        y: 0.2058,
        scale: 0.18,
        rotationDegrees: 202.8473
      },
      {
        symbolId: "balloon",
        x: 0.6416,
        y: 0.4501,
        scale: 0.3,
        rotationDegrees: 124.0625
      },
      {
        symbolId: "money-bag",
        x: 0.7062,
        y: 0.752,
        scale: 0.21,
        rotationDegrees: 59.179
      },
      {
        symbolId: "heart",
        x: 0.399,
        y: 0.7842,
        scale: 0.28,
        rotationDegrees: 75.0597
      }
    ]
  },
  {
    cardId: 3,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.2047,
        y: 0.4184,
        scale: 0.24,
        rotationDegrees: 299.2717
      },
      {
        symbolId: "cloud",
        x: 0.1554,
        y: 0.6477,
        scale: 0.19,
        rotationDegrees: 132.0164
      },
      {
        symbolId: "whale",
        x: 0.3094,
        y: 0.1913,
        scale: 0.21,
        rotationDegrees: 264.0685
      },
      {
        symbolId: "apple",
        x: 0.7305,
        y: 0.7578,
        scale: 0.22,
        rotationDegrees: 358.1431
      },
      {
        symbolId: "lemon",
        x: 0.7838,
        y: 0.4966,
        scale: 0.26,
        rotationDegrees: 252.949
      },
      {
        symbolId: "planet",
        x: 0.4425,
        y: 0.6542,
        scale: 0.3,
        rotationDegrees: 4.0035
      },
      {
        symbolId: "ghost",
        x: 0.5321,
        y: 0.3412,
        scale: 0.28,
        rotationDegrees: 21.6502
      },
      {
        symbolId: "heart",
        x: 0.7677,
        y: 0.2291,
        scale: 0.18,
        rotationDegrees: 30.1228
      }
    ]
  },
  {
    cardId: 4,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.155,
        y: 0.4051,
        scale: 0.19,
        rotationDegrees: 72.0347
      },
      {
        symbolId: "lightning-bolt",
        x: 0.4206,
        y: 0.4978,
        scale: 0.21,
        rotationDegrees: 313.2655
      },
      {
        symbolId: "owl",
        x: 0.3439,
        y: 0.2668,
        scale: 0.24,
        rotationDegrees: 37.7668
      },
      {
        symbolId: "cherries",
        x: 0.1913,
        y: 0.6534,
        scale: 0.26,
        rotationDegrees: 50.9895
      },
      {
        symbolId: "rocket",
        x: 0.801,
        y: 0.5779,
        scale: 0.22,
        rotationDegrees: 326.0016
      },
      {
        symbolId: "flying-saucer",
        x: 0.7295,
        y: 0.8087,
        scale: 0.18,
        rotationDegrees: 99.504
      },
      {
        symbolId: "dice",
        x: 0.6344,
        y: 0.319,
        scale: 0.3,
        rotationDegrees: 334.584
      },
      {
        symbolId: "heart",
        x: 0.4824,
        y: 0.7661,
        scale: 0.28,
        rotationDegrees: 55.1323
      }
    ]
  },
  {
    cardId: 5,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.5574,
        y: 0.865,
        scale: 0.18,
        rotationDegrees: 117.551
      },
      {
        symbolId: "flame",
        x: 0.7171,
        y: 0.6902,
        scale: 0.24,
        rotationDegrees: 303.4146
      },
      {
        symbolId: "turtle",
        x: 0.3079,
        y: 0.7122,
        scale: 0.28,
        rotationDegrees: 336.2027
      },
      {
        symbolId: "watermelon",
        x: 0.2516,
        y: 0.4054,
        scale: 0.26,
        rotationDegrees: 89.1884
      },
      {
        symbolId: "sailboat",
        x: 0.3394,
        y: 0.1637,
        scale: 0.19,
        rotationDegrees: 167.0509
      },
      {
        symbolId: "crown",
        x: 0.5202,
        y: 0.5326,
        scale: 0.21,
        rotationDegrees: 270.6602
      },
      {
        symbolId: "puzzle-piece",
        x: 0.853,
        y: 0.4584,
        scale: 0.22,
        rotationDegrees: 156.7085
      },
      {
        symbolId: "heart",
        x: 0.619,
        y: 0.2768,
        scale: 0.3,
        rotationDegrees: 298.2341
      }
    ]
  },
  {
    cardId: 6,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.2023,
        y: 0.3827,
        scale: 0.18,
        rotationDegrees: 166.3325
      },
      {
        symbolId: "leaf",
        x: 0.3561,
        y: 0.2192,
        scale: 0.21,
        rotationDegrees: 214.6788
      },
      {
        symbolId: "butterfly",
        x: 0.6311,
        y: 0.2441,
        scale: 0.26,
        rotationDegrees: 60.1342
      },
      {
        symbolId: "mushroom",
        x: 0.1901,
        y: 0.6632,
        scale: 0.24,
        rotationDegrees: 238.8052
      },
      {
        symbolId: "bicycle",
        x: 0.7917,
        y: 0.4785,
        scale: 0.22,
        rotationDegrees: 238.1632
      },
      {
        symbolId: "shield",
        x: 0.4063,
        y: 0.7874,
        scale: 0.19,
        rotationDegrees: 72.9825
      },
      {
        symbolId: "star",
        x: 0.6739,
        y: 0.7253,
        scale: 0.28,
        rotationDegrees: 137.9742
      },
      {
        symbolId: "heart",
        x: 0.4574,
        y: 0.489,
        scale: 0.3,
        rotationDegrees: 75.5234
      }
    ]
  },
  {
    cardId: 7,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.6826,
        y: 0.5115,
        scale: 0.3,
        rotationDegrees: 40.1871
      },
      {
        symbolId: "sun",
        x: 0.2575,
        y: 0.6161,
        scale: 0.28,
        rotationDegrees: 156.1288
      },
      {
        symbolId: "cat",
        x: 0.4204,
        y: 0.162,
        scale: 0.24,
        rotationDegrees: 7.0721
      },
      {
        symbolId: "apple",
        x: 0.6454,
        y: 0.811,
        scale: 0.26,
        rotationDegrees: 213.4191
      },
      {
        symbolId: "rocket",
        x: 0.6678,
        y: 0.2313,
        scale: 0.22,
        rotationDegrees: 79.2585
      },
      {
        symbolId: "crown",
        x: 0.2179,
        y: 0.3333,
        scale: 0.21,
        rotationDegrees: 92.3952
      },
      {
        symbolId: "star",
        x: 0.4382,
        y: 0.3909,
        scale: 0.18,
        rotationDegrees: 46.27
      },
      {
        symbolId: "diamond",
        x: 0.4067,
        y: 0.8618,
        scale: 0.19,
        rotationDegrees: 111.2137
      }
    ]
  },
  {
    cardId: 8,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.4789,
        y: 0.4827,
        scale: 0.22,
        rotationDegrees: 335.4613
      },
      {
        symbolId: "moon",
        x: 0.2338,
        y: 0.3459,
        scale: 0.3,
        rotationDegrees: 224.1594
      },
      {
        symbolId: "whale",
        x: 0.7752,
        y: 0.4048,
        scale: 0.28,
        rotationDegrees: 115.6143
      },
      {
        symbolId: "cherries",
        x: 0.4308,
        y: 0.8162,
        scale: 0.26,
        rotationDegrees: 251.8226
      },
      {
        symbolId: "sailboat",
        x: 0.416,
        y: 0.1288,
        scale: 0.18,
        rotationDegrees: 351.3555
      },
      {
        symbolId: "shield",
        x: 0.1823,
        y: 0.6248,
        scale: 0.21,
        rotationDegrees: 333.6844
      },
      {
        symbolId: "test-tube",
        x: 0.684,
        y: 0.6726,
        scale: 0.24,
        rotationDegrees: 108.8567
      },
      {
        symbolId: "diamond",
        x: 0.6606,
        y: 0.1742,
        scale: 0.19,
        rotationDegrees: 184.3214
      }
    ]
  },
  {
    cardId: 9,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.1862,
        y: 0.6844,
        scale: 0.21,
        rotationDegrees: 26.4441
      },
      {
        symbolId: "cloud",
        x: 0.7327,
        y: 0.5574,
        scale: 0.24,
        rotationDegrees: 246.8778
      },
      {
        symbolId: "owl",
        x: 0.4466,
        y: 0.5983,
        scale: 0.3,
        rotationDegrees: 209.971
      },
      {
        symbolId: "watermelon",
        x: 0.8551,
        y: 0.3615,
        scale: 0.18,
        rotationDegrees: 112.3027
      },
      {
        symbolId: "bicycle",
        x: 0.6329,
        y: 0.8099,
        scale: 0.22,
        rotationDegrees: 357.6135
      },
      {
        symbolId: "airplane",
        x: 0.6151,
        y: 0.2151,
        scale: 0.28,
        rotationDegrees: 211.5223
      },
      {
        symbolId: "wand",
        x: 0.3824,
        y: 0.8608,
        scale: 0.19,
        rotationDegrees: 211.6345
      },
      {
        symbolId: "diamond",
        x: 0.209,
        y: 0.3679,
        scale: 0.26,
        rotationDegrees: 121.0206
      }
    ]
  },
  {
    cardId: 10,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.8214,
        y: 0.4617,
        scale: 0.3,
        rotationDegrees: 342.0435
      },
      {
        symbolId: "lightning-bolt",
        x: 0.1444,
        y: 0.5319,
        scale: 0.22,
        rotationDegrees: 82.7305
      },
      {
        symbolId: "turtle",
        x: 0.2241,
        y: 0.7583,
        scale: 0.19,
        rotationDegrees: 268.729
      },
      {
        symbolId: "mushroom",
        x: 0.2682,
        y: 0.2317,
        scale: 0.24,
        rotationDegrees: 248.7512
      },
      {
        symbolId: "cupcake",
        x: 0.3826,
        y: 0.4311,
        scale: 0.18,
        rotationDegrees: 187.4434
      },
      {
        symbolId: "train",
        x: 0.7262,
        y: 0.7596,
        scale: 0.21,
        rotationDegrees: 34.8679
      },
      {
        symbolId: "money-bag",
        x: 0.5588,
        y: 0.2194,
        scale: 0.28,
        rotationDegrees: 270.4044
      },
      {
        symbolId: "diamond",
        x: 0.464,
        y: 0.6708,
        scale: 0.26,
        rotationDegrees: 173.0298
      }
    ]
  },
  {
    cardId: 11,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.1788,
        y: 0.696,
        scale: 0.19,
        rotationDegrees: 239.8823
      },
      {
        symbolId: "flame",
        x: 0.4561,
        y: 0.6708,
        scale: 0.3,
        rotationDegrees: 86.7535
      },
      {
        symbolId: "butterfly",
        x: 0.718,
        y: 0.2656,
        scale: 0.24,
        rotationDegrees: 11.1161
      },
      {
        symbolId: "frog",
        x: 0.8202,
        y: 0.5282,
        scale: 0.26,
        rotationDegrees: 14.7021
      },
      {
        symbolId: "pretzel",
        x: 0.5156,
        y: 0.4112,
        scale: 0.18,
        rotationDegrees: 338.294
      },
      {
        symbolId: "balloon",
        x: 0.7045,
        y: 0.792,
        scale: 0.21,
        rotationDegrees: 187.9398
      },
      {
        symbolId: "ghost",
        x: 0.1657,
        y: 0.4169,
        scale: 0.22,
        rotationDegrees: 231.7799
      },
      {
        symbolId: "diamond",
        x: 0.3537,
        y: 0.2219,
        scale: 0.28,
        rotationDegrees: 288.6168
      }
    ]
  },
  {
    cardId: 12,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.2936,
        y: 0.8015,
        scale: 0.21,
        rotationDegrees: 278.7093
      },
      {
        symbolId: "leaf",
        x: 0.7661,
        y: 0.4361,
        scale: 0.28,
        rotationDegrees: 113.3924
      },
      {
        symbolId: "cactus",
        x: 0.4675,
        y: 0.1453,
        scale: 0.22,
        rotationDegrees: 198.8986
      },
      {
        symbolId: "snail",
        x: 0.8031,
        y: 0.7117,
        scale: 0.19,
        rotationDegrees: 30.7724
      },
      {
        symbolId: "carrot",
        x: 0.1598,
        y: 0.584,
        scale: 0.24,
        rotationDegrees: 141.0318
      },
      {
        symbolId: "planet",
        x: 0.5568,
        y: 0.7125,
        scale: 0.26,
        rotationDegrees: 128.644
      },
      {
        symbolId: "dice",
        x: 0.4048,
        y: 0.4279,
        scale: 0.3,
        rotationDegrees: 177.4926
      },
      {
        symbolId: "diamond",
        x: 0.6882,
        y: 0.1948,
        scale: 0.18,
        rotationDegrees: 293.3587
      }
    ]
  },
  {
    cardId: 13,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.4094,
        y: 0.5156,
        scale: 0.18,
        rotationDegrees: 263.4979
      },
      {
        symbolId: "camera",
        x: 0.6829,
        y: 0.4271,
        scale: 0.28,
        rotationDegrees: 266.801
      },
      {
        symbolId: "snowflake",
        x: 0.5252,
        y: 0.7283,
        scale: 0.26,
        rotationDegrees: 103.2853
      },
      {
        symbolId: "bee",
        x: 0.2717,
        y: 0.7997,
        scale: 0.19,
        rotationDegrees: 60.5231
      },
      {
        symbolId: "lemon",
        x: 0.793,
        y: 0.716,
        scale: 0.21,
        rotationDegrees: 225.6349
      },
      {
        symbolId: "flying-saucer",
        x: 0.5415,
        y: 0.1675,
        scale: 0.22,
        rotationDegrees: 51.6935
      },
      {
        symbolId: "puzzle-piece",
        x: 0.2753,
        y: 0.2885,
        scale: 0.3,
        rotationDegrees: 310.2538
      },
      {
        symbolId: "diamond",
        x: 0.1708,
        y: 0.5854,
        scale: 0.24,
        rotationDegrees: 258.0369
      }
    ]
  },
  {
    cardId: 14,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.4443,
        y: 0.842,
        scale: 0.22,
        rotationDegrees: 46.7014
      },
      {
        symbolId: "moon",
        x: 0.234,
        y: 0.7366,
        scale: 0.19,
        rotationDegrees: 245.7908
      },
      {
        symbolId: "owl",
        x: 0.1389,
        y: 0.4836,
        scale: 0.18,
        rotationDegrees: 344.1574
      },
      {
        symbolId: "mushroom",
        x: 0.6889,
        y: 0.7026,
        scale: 0.28,
        rotationDegrees: 99.9738
      },
      {
        symbolId: "pretzel",
        x: 0.6058,
        y: 0.1761,
        scale: 0.26,
        rotationDegrees: 304.2539
      },
      {
        symbolId: "planet",
        x: 0.2851,
        y: 0.2603,
        scale: 0.21,
        rotationDegrees: 323.3127
      },
      {
        symbolId: "puzzle-piece",
        x: 0.8137,
        y: 0.4002,
        scale: 0.24,
        rotationDegrees: 170.188
      },
      {
        symbolId: "cyclone",
        x: 0.4053,
        y: 0.5314,
        scale: 0.3,
        rotationDegrees: 220.8716
      }
    ]
  },
  {
    cardId: 15,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.7822,
        y: 0.4155,
        scale: 0.24,
        rotationDegrees: 349.2059
      },
      {
        symbolId: "cloud",
        x: 0.2097,
        y: 0.3104,
        scale: 0.22,
        rotationDegrees: 323.4083
      },
      {
        symbolId: "turtle",
        x: 0.6829,
        y: 0.7701,
        scale: 0.28,
        rotationDegrees: 93.1534
      },
      {
        symbolId: "frog",
        x: 0.1252,
        y: 0.5268,
        scale: 0.19,
        rotationDegrees: 352.8475
      },
      {
        symbolId: "carrot",
        x: 0.3127,
        y: 0.7406,
        scale: 0.26,
        rotationDegrees: 200.9213
      },
      {
        symbolId: "flying-saucer",
        x: 0.4914,
        y: 0.3833,
        scale: 0.3,
        rotationDegrees: 102.4439
      },
      {
        symbolId: "star",
        x: 0.4016,
        y: 0.132,
        scale: 0.18,
        rotationDegrees: 64.353
      },
      {
        symbolId: "cyclone",
        x: 0.673,
        y: 0.1761,
        scale: 0.21,
        rotationDegrees: 323.7675
      }
    ]
  },
  {
    cardId: 16,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.2846,
        y: 0.2925,
        scale: 0.26,
        rotationDegrees: 37.3567
      },
      {
        symbolId: "lightning-bolt",
        x: 0.3976,
        y: 0.5207,
        scale: 0.21,
        rotationDegrees: 264.3511
      },
      {
        symbolId: "butterfly",
        x: 0.5528,
        y: 0.1791,
        scale: 0.22,
        rotationDegrees: 198.9662
      },
      {
        symbolId: "snail",
        x: 0.6783,
        y: 0.5206,
        scale: 0.3,
        rotationDegrees: 251.3527
      },
      {
        symbolId: "lemon",
        x: 0.4863,
        y: 0.7866,
        scale: 0.28,
        rotationDegrees: 272.8235
      },
      {
        symbolId: "crown",
        x: 0.1865,
        y: 0.643,
        scale: 0.24,
        rotationDegrees: 229.8727
      },
      {
        symbolId: "test-tube",
        x: 0.764,
        y: 0.7735,
        scale: 0.18,
        rotationDegrees: 219.5743
      },
      {
        symbolId: "cyclone",
        x: 0.8001,
        y: 0.2862,
        scale: 0.19,
        rotationDegrees: 331.1186
      }
    ]
  },
  {
    cardId: 17,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.3021,
        y: 0.2059,
        scale: 0.22,
        rotationDegrees: 148.1331
      },
      {
        symbolId: "flame",
        x: 0.4256,
        y: 0.8356,
        scale: 0.24,
        rotationDegrees: 12.7354
      },
      {
        symbolId: "cactus",
        x: 0.8251,
        y: 0.3062,
        scale: 0.18,
        rotationDegrees: 325.5568
      },
      {
        symbolId: "bee",
        x: 0.4863,
        y: 0.5863,
        scale: 0.21,
        rotationDegrees: 178.3734
      },
      {
        symbolId: "rocket",
        x: 0.2027,
        y: 0.534,
        scale: 0.28,
        rotationDegrees: 124.2574
      },
      {
        symbolId: "shield",
        x: 0.5531,
        y: 0.3377,
        scale: 0.26,
        rotationDegrees: 184.9959
      },
      {
        symbolId: "wand",
        x: 0.7925,
        y: 0.5743,
        scale: 0.3,
        rotationDegrees: 101.6308
      },
      {
        symbolId: "cyclone",
        x: 0.6599,
        y: 0.8131,
        scale: 0.19,
        rotationDegrees: 320.4957
      }
    ]
  },
  {
    cardId: 18,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.5981,
        y: 0.3371,
        scale: 0.3,
        rotationDegrees: 153.8707
      },
      {
        symbolId: "leaf",
        x: 0.4462,
        y: 0.8655,
        scale: 0.21,
        rotationDegrees: 339.3405
      },
      {
        symbolId: "snowflake",
        x: 0.1288,
        y: 0.4917,
        scale: 0.19,
        rotationDegrees: 339.8841
      },
      {
        symbolId: "apple",
        x: 0.2986,
        y: 0.3233,
        scale: 0.24,
        rotationDegrees: 292.464
      },
      {
        symbolId: "sailboat",
        x: 0.3603,
        y: 0.5961,
        scale: 0.28,
        rotationDegrees: 280.8173
      },
      {
        symbolId: "airplane",
        x: 0.4431,
        y: 0.1305,
        scale: 0.18,
        rotationDegrees: 61.0419
      },
      {
        symbolId: "money-bag",
        x: 0.827,
        y: 0.4969,
        scale: 0.22,
        rotationDegrees: 154.6074
      },
      {
        symbolId: "cyclone",
        x: 0.685,
        y: 0.7607,
        scale: 0.26,
        rotationDegrees: 87.1039
      }
    ]
  },
  {
    cardId: 19,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.3296,
        y: 0.8294,
        scale: 0.19,
        rotationDegrees: 291.6757
      },
      {
        symbolId: "camera",
        x: 0.5043,
        y: 0.6228,
        scale: 0.3,
        rotationDegrees: 283.029
      },
      {
        symbolId: "cat",
        x: 0.3963,
        y: 0.3162,
        scale: 0.28,
        rotationDegrees: 341.5359
      },
      {
        symbolId: "cherries",
        x: 0.8033,
        y: 0.7092,
        scale: 0.21,
        rotationDegrees: 52.6056
      },
      {
        symbolId: "bicycle",
        x: 0.7087,
        y: 0.2209,
        scale: 0.22,
        rotationDegrees: 37.7145
      },
      {
        symbolId: "train",
        x: 0.1972,
        y: 0.6258,
        scale: 0.24,
        rotationDegrees: 6.4441
      },
      {
        symbolId: "ghost",
        x: 0.8344,
        y: 0.4481,
        scale: 0.26,
        rotationDegrees: 329.9102
      },
      {
        symbolId: "cyclone",
        x: 0.147,
        y: 0.4004,
        scale: 0.18,
        rotationDegrees: 336.5167
      }
    ]
  },
  {
    cardId: 20,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.8549,
        y: 0.602,
        scale: 0.21,
        rotationDegrees: 218.3874
      },
      {
        symbolId: "sun",
        x: 0.819,
        y: 0.3549,
        scale: 0.24,
        rotationDegrees: 301.5095
      },
      {
        symbolId: "whale",
        x: 0.6539,
        y: 0.1557,
        scale: 0.18,
        rotationDegrees: 269.2114
      },
      {
        symbolId: "watermelon",
        x: 0.3222,
        y: 0.745,
        scale: 0.22,
        rotationDegrees: 143.7086
      },
      {
        symbolId: "cupcake",
        x: 0.5644,
        y: 0.5975,
        scale: 0.28,
        rotationDegrees: 358.8088
      },
      {
        symbolId: "balloon",
        x: 0.1737,
        y: 0.467,
        scale: 0.26,
        rotationDegrees: 155.1558
      },
      {
        symbolId: "dice",
        x: 0.6371,
        y: 0.8451,
        scale: 0.19,
        rotationDegrees: 5.2612
      },
      {
        symbolId: "cyclone",
        x: 0.4187,
        y: 0.2935,
        scale: 0.3,
        rotationDegrees: 67.3832
      }
    ]
  },
  {
    cardId: 21,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.3534,
        y: 0.8147,
        scale: 0.19,
        rotationDegrees: 143.3691
      },
      {
        symbolId: "cloud",
        x: 0.2008,
        y: 0.6448,
        scale: 0.21,
        rotationDegrees: 358.4145
      },
      {
        symbolId: "butterfly",
        x: 0.6511,
        y: 0.8212,
        scale: 0.18,
        rotationDegrees: 41.1937
      },
      {
        symbolId: "bee",
        x: 0.8164,
        y: 0.6073,
        scale: 0.24,
        rotationDegrees: 169.4376
      },
      {
        symbolId: "sailboat",
        x: 0.6834,
        y: 0.3061,
        scale: 0.3,
        rotationDegrees: 46.0519
      },
      {
        symbolId: "train",
        x: 0.4373,
        y: 0.1601,
        scale: 0.22,
        rotationDegrees: 131.5951
      },
      {
        symbolId: "dice",
        x: 0.2455,
        y: 0.3452,
        scale: 0.26,
        rotationDegrees: 143.3351
      },
      {
        symbolId: "water-drop",
        x: 0.5186,
        y: 0.5711,
        scale: 0.28,
        rotationDegrees: 259.4049
      }
    ]
  },
  {
    cardId: 22,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.3866,
        y: 0.1856,
        scale: 0.19,
        rotationDegrees: 302.4555
      },
      {
        symbolId: "lightning-bolt",
        x: 0.6312,
        y: 0.2519,
        scale: 0.26,
        rotationDegrees: 282.1627
      },
      {
        symbolId: "cactus",
        x: 0.8598,
        y: 0.3809,
        scale: 0.18,
        rotationDegrees: 357.8469
      },
      {
        symbolId: "apple",
        x: 0.509,
        y: 0.5432,
        scale: 0.3,
        rotationDegrees: 128.0818
      },
      {
        symbolId: "bicycle",
        x: 0.5425,
        y: 0.8543,
        scale: 0.21,
        rotationDegrees: 142.7852
      },
      {
        symbolId: "balloon",
        x: 0.7931,
        y: 0.6719,
        scale: 0.24,
        rotationDegrees: 113.2522
      },
      {
        symbolId: "puzzle-piece",
        x: 0.2261,
        y: 0.3971,
        scale: 0.28,
        rotationDegrees: 257.7398
      },
      {
        symbolId: "water-drop",
        x: 0.3171,
        y: 0.7853,
        scale: 0.22,
        rotationDegrees: 162.8631
      }
    ]
  },
  {
    cardId: 23,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.2166,
        y: 0.639,
        scale: 0.21,
        rotationDegrees: 315.652
      },
      {
        symbolId: "flame",
        x: 0.3842,
        y: 0.1554,
        scale: 0.19,
        rotationDegrees: 211.2345
      },
      {
        symbolId: "snowflake",
        x: 0.7337,
        y: 0.6718,
        scale: 0.24,
        rotationDegrees: 304.0755
      },
      {
        symbolId: "cherries",
        x: 0.1954,
        y: 0.3666,
        scale: 0.26,
        rotationDegrees: 112.2343
      },
      {
        symbolId: "cupcake",
        x: 0.5183,
        y: 0.3996,
        scale: 0.28,
        rotationDegrees: 289.7098
      },
      {
        symbolId: "planet",
        x: 0.6289,
        y: 0.1737,
        scale: 0.18,
        rotationDegrees: 215.2879
      },
      {
        symbolId: "star",
        x: 0.462,
        y: 0.7725,
        scale: 0.3,
        rotationDegrees: 305.5296
      },
      {
        symbolId: "water-drop",
        x: 0.8172,
        y: 0.3295,
        scale: 0.22,
        rotationDegrees: 152.3137
      }
    ]
  },
  {
    cardId: 24,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.5203,
        y: 0.805,
        scale: 0.24,
        rotationDegrees: 310.783
      },
      {
        symbolId: "leaf",
        x: 0.7879,
        y: 0.7505,
        scale: 0.18,
        rotationDegrees: 145.3986
      },
      {
        symbolId: "cat",
        x: 0.4015,
        y: 0.2,
        scale: 0.3,
        rotationDegrees: 355.0062
      },
      {
        symbolId: "watermelon",
        x: 0.6722,
        y: 0.5293,
        scale: 0.28,
        rotationDegrees: 175.9665
      },
      {
        symbolId: "pretzel",
        x: 0.2744,
        y: 0.6699,
        scale: 0.26,
        rotationDegrees: 60.8403
      },
      {
        symbolId: "flying-saucer",
        x: 0.7018,
        y: 0.2527,
        scale: 0.22,
        rotationDegrees: 218.6978
      },
      {
        symbolId: "test-tube",
        x: 0.4236,
        y: 0.4635,
        scale: 0.19,
        rotationDegrees: 318.418
      },
      {
        symbolId: "water-drop",
        x: 0.1916,
        y: 0.4265,
        scale: 0.21,
        rotationDegrees: 267.798
      }
    ]
  },
  {
    cardId: 25,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.1966,
        y: 0.2689,
        scale: 0.18,
        rotationDegrees: 13.3591
      },
      {
        symbolId: "camera",
        x: 0.7672,
        y: 0.3533,
        scale: 0.22,
        rotationDegrees: 167.2273
      },
      {
        symbolId: "whale",
        x: 0.7785,
        y: 0.6453,
        scale: 0.28,
        rotationDegrees: 127.0008
      },
      {
        symbolId: "mushroom",
        x: 0.1844,
        y: 0.5028,
        scale: 0.24,
        rotationDegrees: 293.0447
      },
      {
        symbolId: "carrot",
        x: 0.4221,
        y: 0.6649,
        scale: 0.26,
        rotationDegrees: 151.6498
      },
      {
        symbolId: "crown",
        x: 0.6126,
        y: 0.8511,
        scale: 0.21,
        rotationDegrees: 254.7684
      },
      {
        symbolId: "wand",
        x: 0.6526,
        y: 0.1575,
        scale: 0.19,
        rotationDegrees: 272.5244
      },
      {
        symbolId: "water-drop",
        x: 0.4515,
        y: 0.3475,
        scale: 0.3,
        rotationDegrees: 82.8576
      }
    ]
  },
  {
    cardId: 26,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.5444,
        y: 0.6635,
        scale: 0.3,
        rotationDegrees: 177.8251
      },
      {
        symbolId: "sun",
        x: 0.6337,
        y: 0.3251,
        scale: 0.28,
        rotationDegrees: 342.8554
      },
      {
        symbolId: "owl",
        x: 0.4008,
        y: 0.4321,
        scale: 0.19,
        rotationDegrees: 12.6993
      },
      {
        symbolId: "frog",
        x: 0.8554,
        y: 0.5346,
        scale: 0.22,
        rotationDegrees: 242.5477
      },
      {
        symbolId: "lemon",
        x: 0.2192,
        y: 0.6402,
        scale: 0.26,
        rotationDegrees: 261.9453
      },
      {
        symbolId: "shield",
        x: 0.1545,
        y: 0.3907,
        scale: 0.21,
        rotationDegrees: 325.039
      },
      {
        symbolId: "money-bag",
        x: 0.3172,
        y: 0.202,
        scale: 0.24,
        rotationDegrees: 252.77
      },
      {
        symbolId: "water-drop",
        x: 0.3513,
        y: 0.8461,
        scale: 0.18,
        rotationDegrees: 233.3307
      }
    ]
  },
  {
    cardId: 27,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.5566,
        y: 0.8675,
        scale: 0.18,
        rotationDegrees: 297.3634
      },
      {
        symbolId: "moon",
        x: 0.5496,
        y: 0.5983,
        scale: 0.19,
        rotationDegrees: 128.3345
      },
      {
        symbolId: "turtle",
        x: 0.5604,
        y: 0.3313,
        scale: 0.3,
        rotationDegrees: 183.2703
      },
      {
        symbolId: "snail",
        x: 0.3412,
        y: 0.7621,
        scale: 0.26,
        rotationDegrees: 356.5622
      },
      {
        symbolId: "rocket",
        x: 0.7661,
        y: 0.7201,
        scale: 0.24,
        rotationDegrees: 273.8111
      },
      {
        symbolId: "airplane",
        x: 0.1709,
        y: 0.4433,
        scale: 0.28,
        rotationDegrees: 192.9164
      },
      {
        symbolId: "ghost",
        x: 0.8416,
        y: 0.4829,
        scale: 0.22,
        rotationDegrees: 187.4261
      },
      {
        symbolId: "water-drop",
        x: 0.3315,
        y: 0.182,
        scale: 0.21,
        rotationDegrees: 251.7903
      }
    ]
  },
  {
    cardId: 28,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.5114,
        y: 0.1225,
        scale: 0.19,
        rotationDegrees: 221.5423
      },
      {
        symbolId: "lightning-bolt",
        x: 0.5113,
        y: 0.5897,
        scale: 0.22,
        rotationDegrees: 1.4783
      },
      {
        symbolId: "snowflake",
        x: 0.5371,
        y: 0.8675,
        scale: 0.21,
        rotationDegrees: 88.2126
      },
      {
        symbolId: "watermelon",
        x: 0.1413,
        y: 0.4483,
        scale: 0.18,
        rotationDegrees: 326.9789
      },
      {
        symbolId: "carrot",
        x: 0.2461,
        y: 0.6803,
        scale: 0.26,
        rotationDegrees: 313.3657
      },
      {
        symbolId: "shield",
        x: 0.7565,
        y: 0.6525,
        scale: 0.24,
        rotationDegrees: 245.0332
      },
      {
        symbolId: "ghost",
        x: 0.3702,
        y: 0.3401,
        scale: 0.28,
        rotationDegrees: 265.9419
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.7458,
        y: 0.3087,
        scale: 0.3,
        rotationDegrees: 296.4289
      }
    ]
  },
  {
    cardId: 29,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.1971,
        y: 0.6179,
        scale: 0.19,
        rotationDegrees: 315.712
      },
      {
        symbolId: "flame",
        x: 0.3789,
        y: 0.7964,
        scale: 0.26,
        rotationDegrees: 319.2569
      },
      {
        symbolId: "cat",
        x: 0.8112,
        y: 0.6827,
        scale: 0.18,
        rotationDegrees: 309.1188
      },
      {
        symbolId: "mushroom",
        x: 0.8291,
        y: 0.434,
        scale: 0.22,
        rotationDegrees: 91.9608
      },
      {
        symbolId: "lemon",
        x: 0.2906,
        y: 0.3367,
        scale: 0.28,
        rotationDegrees: 347.8391
      },
      {
        symbolId: "airplane",
        x: 0.6462,
        y: 0.8357,
        scale: 0.21,
        rotationDegrees: 155.05
      },
      {
        symbolId: "dice",
        x: 0.6078,
        y: 0.2242,
        scale: 0.24,
        rotationDegrees: 137.5485
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.5531,
        y: 0.5445,
        scale: 0.3,
        rotationDegrees: 326.7855
      }
    ]
  },
  {
    cardId: 30,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.8106,
        y: 0.2966,
        scale: 0.19,
        rotationDegrees: 110.1406
      },
      {
        symbolId: "leaf",
        x: 0.5338,
        y: 0.1337,
        scale: 0.21,
        rotationDegrees: 198.3416
      },
      {
        symbolId: "whale",
        x: 0.5791,
        y: 0.3993,
        scale: 0.28,
        rotationDegrees: 204.6812
      },
      {
        symbolId: "frog",
        x: 0.7616,
        y: 0.6616,
        scale: 0.3,
        rotationDegrees: 231.0805
      },
      {
        symbolId: "rocket",
        x: 0.2229,
        y: 0.6906,
        scale: 0.26,
        rotationDegrees: 11.2434
      },
      {
        symbolId: "train",
        x: 0.5452,
        y: 0.8615,
        scale: 0.22,
        rotationDegrees: 131.3161
      },
      {
        symbolId: "puzzle-piece",
        x: 0.4655,
        y: 0.6462,
        scale: 0.18,
        rotationDegrees: 120.6117
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.273,
        y: 0.3478,
        scale: 0.24,
        rotationDegrees: 227.775
      }
    ]
  },
  {
    cardId: 31,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.3803,
        y: 0.1667,
        scale: 0.24,
        rotationDegrees: 305.6989
      },
      {
        symbolId: "camera",
        x: 0.6881,
        y: 0.6606,
        scale: 0.28,
        rotationDegrees: 62.0011
      },
      {
        symbolId: "owl",
        x: 0.2374,
        y: 0.4364,
        scale: 0.3,
        rotationDegrees: 353.6776
      },
      {
        symbolId: "snail",
        x: 0.8378,
        y: 0.4066,
        scale: 0.21,
        rotationDegrees: 162.4827
      },
      {
        symbolId: "sailboat",
        x: 0.3482,
        y: 0.8235,
        scale: 0.22,
        rotationDegrees: 195.9796
      },
      {
        symbolId: "balloon",
        x: 0.5537,
        y: 0.4401,
        scale: 0.19,
        rotationDegrees: 320.1667
      },
      {
        symbolId: "star",
        x: 0.1649,
        y: 0.6848,
        scale: 0.18,
        rotationDegrees: 283.0837
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.6551,
        y: 0.2028,
        scale: 0.26,
        rotationDegrees: 303.4495
      }
    ]
  },
  {
    cardId: 32,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.3467,
        y: 0.6469,
        scale: 0.26,
        rotationDegrees: 353.9476
      },
      {
        symbolId: "sun",
        x: 0.7735,
        y: 0.2777,
        scale: 0.24,
        rotationDegrees: 275.6037
      },
      {
        symbolId: "turtle",
        x: 0.388,
        y: 0.2589,
        scale: 0.28,
        rotationDegrees: 66.0512
      },
      {
        symbolId: "bee",
        x: 0.866,
        y: 0.4866,
        scale: 0.18,
        rotationDegrees: 251.5866
      },
      {
        symbolId: "bicycle",
        x: 0.6972,
        y: 0.6846,
        scale: 0.3,
        rotationDegrees: 246.7304
      },
      {
        symbolId: "planet",
        x: 0.4851,
        y: 0.8663,
        scale: 0.21,
        rotationDegrees: 3.5407
      },
      {
        symbolId: "test-tube",
        x: 0.1598,
        y: 0.4485,
        scale: 0.22,
        rotationDegrees: 144.1566
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.5442,
        y: 0.4697,
        scale: 0.19,
        rotationDegrees: 103.894
      }
    ]
  },
  {
    cardId: 33,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.3075,
        y: 0.6595,
        scale: 0.26,
        rotationDegrees: 321.5728
      },
      {
        symbolId: "moon",
        x: 0.664,
        y: 0.6844,
        scale: 0.3,
        rotationDegrees: 325.186
      },
      {
        symbolId: "butterfly",
        x: 0.459,
        y: 0.1377,
        scale: 0.22,
        rotationDegrees: 212.1616
      },
      {
        symbolId: "apple",
        x: 0.7418,
        y: 0.3471,
        scale: 0.24,
        rotationDegrees: 137.1613
      },
      {
        symbolId: "cupcake",
        x: 0.5066,
        y: 0.4454,
        scale: 0.21,
        rotationDegrees: 135.2285
      },
      {
        symbolId: "flying-saucer",
        x: 0.8785,
        y: 0.5328,
        scale: 0.18,
        rotationDegrees: 211.7659
      },
      {
        symbolId: "wand",
        x: 0.4385,
        y: 0.8746,
        scale: 0.19,
        rotationDegrees: 180.7197
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.2653,
        y: 0.3303,
        scale: 0.28,
        rotationDegrees: 61.7797
      }
    ]
  },
  {
    cardId: 34,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.6138,
        y: 0.1757,
        scale: 0.24,
        rotationDegrees: 178.4214
      },
      {
        symbolId: "cloud",
        x: 0.4325,
        y: 0.4623,
        scale: 0.3,
        rotationDegrees: 254.3187
      },
      {
        symbolId: "cactus",
        x: 0.147,
        y: 0.5431,
        scale: 0.18,
        rotationDegrees: 10.4585
      },
      {
        symbolId: "cherries",
        x: 0.5743,
        y: 0.7427,
        scale: 0.19,
        rotationDegrees: 341.0376
      },
      {
        symbolId: "pretzel",
        x: 0.2867,
        y: 0.2233,
        scale: 0.21,
        rotationDegrees: 260.0946
      },
      {
        symbolId: "crown",
        x: 0.8044,
        y: 0.354,
        scale: 0.22,
        rotationDegrees: 71.3966
      },
      {
        symbolId: "money-bag",
        x: 0.3026,
        y: 0.7334,
        scale: 0.26,
        rotationDegrees: 19.3721
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.8052,
        y: 0.6311,
        scale: 0.28,
        rotationDegrees: 179.9698
      }
    ]
  },
  {
    cardId: 35,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.8394,
        y: 0.4788,
        scale: 0.22,
        rotationDegrees: 67.4353
      },
      {
        symbolId: "flame",
        x: 0.4522,
        y: 0.813,
        scale: 0.28,
        rotationDegrees: 67.8331
      },
      {
        symbolId: "whale",
        x: 0.4635,
        y: 0.1205,
        scale: 0.18,
        rotationDegrees: 8.9273
      },
      {
        symbolId: "snail",
        x: 0.2468,
        y: 0.2442,
        scale: 0.21,
        rotationDegrees: 170.6189
      },
      {
        symbolId: "bicycle",
        x: 0.1735,
        y: 0.5116,
        scale: 0.26,
        rotationDegrees: 114.0375
      },
      {
        symbolId: "flying-saucer",
        x: 0.5072,
        y: 0.3776,
        scale: 0.3,
        rotationDegrees: 290.6931
      },
      {
        symbolId: "money-bag",
        x: 0.7113,
        y: 0.202,
        scale: 0.19,
        rotationDegrees: 14.0319
      },
      {
        symbolId: "eye",
        x: 0.7343,
        y: 0.7174,
        scale: 0.24,
        rotationDegrees: 308.9774
      }
    ]
  },
  {
    cardId: 36,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.1708,
        y: 0.6119,
        scale: 0.22,
        rotationDegrees: 168.6106
      },
      {
        symbolId: "leaf",
        x: 0.422,
        y: 0.856,
        scale: 0.19,
        rotationDegrees: 247.8991
      },
      {
        symbolId: "owl",
        x: 0.4917,
        y: 0.1399,
        scale: 0.21,
        rotationDegrees: 312.5306
      },
      {
        symbolId: "bee",
        x: 0.6692,
        y: 0.3566,
        scale: 0.3,
        rotationDegrees: 33.5956
      },
      {
        symbolId: "cupcake",
        x: 0.2791,
        y: 0.3055,
        scale: 0.28,
        rotationDegrees: 46.4034
      },
      {
        symbolId: "crown",
        x: 0.4702,
        y: 0.6279,
        scale: 0.24,
        rotationDegrees: 352.5083
      },
      {
        symbolId: "ghost",
        x: 0.8679,
        y: 0.5457,
        scale: 0.18,
        rotationDegrees: 59.7592
      },
      {
        symbolId: "eye",
        x: 0.7149,
        y: 0.7618,
        scale: 0.26,
        rotationDegrees: 320.3089
      }
    ]
  },
  {
    cardId: 37,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.6002,
        y: 0.1348,
        scale: 0.19,
        rotationDegrees: 55.4681
      },
      {
        symbolId: "camera",
        x: 0.7122,
        y: 0.5964,
        scale: 0.22,
        rotationDegrees: 259.7665
      },
      {
        symbolId: "turtle",
        x: 0.2344,
        y: 0.2662,
        scale: 0.24,
        rotationDegrees: 317.6355
      },
      {
        symbolId: "apple",
        x: 0.5191,
        y: 0.384,
        scale: 0.28,
        rotationDegrees: 173.7703
      },
      {
        symbolId: "pretzel",
        x: 0.2127,
        y: 0.5792,
        scale: 0.3,
        rotationDegrees: 10.958
      },
      {
        symbolId: "shield",
        x: 0.4723,
        y: 0.8154,
        scale: 0.26,
        rotationDegrees: 136.9713
      },
      {
        symbolId: "dice",
        x: 0.7817,
        y: 0.364,
        scale: 0.21,
        rotationDegrees: 325.0841
      },
      {
        symbolId: "eye",
        x: 0.715,
        y: 0.8189,
        scale: 0.18,
        rotationDegrees: 177.7253
      }
    ]
  },
  {
    cardId: 38,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.3714,
        y: 0.4511,
        scale: 0.22,
        rotationDegrees: 192.5722
      },
      {
        symbolId: "sun",
        x: 0.7324,
        y: 0.6418,
        scale: 0.26,
        rotationDegrees: 125.3439
      },
      {
        symbolId: "butterfly",
        x: 0.8572,
        y: 0.425,
        scale: 0.19,
        rotationDegrees: 337.8096
      },
      {
        symbolId: "cherries",
        x: 0.3987,
        y: 0.7443,
        scale: 0.3,
        rotationDegrees: 263.2539
      },
      {
        symbolId: "carrot",
        x: 0.623,
        y: 0.3908,
        scale: 0.24,
        rotationDegrees: 307.7446
      },
      {
        symbolId: "airplane",
        x: 0.3988,
        y: 0.1816,
        scale: 0.28,
        rotationDegrees: 357.8239
      },
      {
        symbolId: "puzzle-piece",
        x: 0.1402,
        y: 0.487,
        scale: 0.21,
        rotationDegrees: 228.9558
      },
      {
        symbolId: "eye",
        x: 0.656,
        y: 0.1592,
        scale: 0.18,
        rotationDegrees: 127.691
      }
    ]
  },
  {
    cardId: 39,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.4248,
        y: 0.2085,
        scale: 0.28,
        rotationDegrees: 1.7444
      },
      {
        symbolId: "moon",
        x: 0.68,
        y: 0.8035,
        scale: 0.18,
        rotationDegrees: 124.8252
      },
      {
        symbolId: "cactus",
        x: 0.8036,
        y: 0.37,
        scale: 0.26,
        rotationDegrees: 280.7712
      },
      {
        symbolId: "watermelon",
        x: 0.8353,
        y: 0.6264,
        scale: 0.22,
        rotationDegrees: 186.5039
      },
      {
        symbolId: "lemon",
        x: 0.4514,
        y: 0.8572,
        scale: 0.19,
        rotationDegrees: 102.4459
      },
      {
        symbolId: "train",
        x: 0.207,
        y: 0.577,
        scale: 0.24,
        rotationDegrees: 66.1585
      },
      {
        symbolId: "star",
        x: 0.1819,
        y: 0.3261,
        scale: 0.21,
        rotationDegrees: 330.6513
      },
      {
        symbolId: "eye",
        x: 0.5246,
        y: 0.5881,
        scale: 0.3,
        rotationDegrees: 102.6811
      }
    ]
  },
  {
    cardId: 40,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.4871,
        y: 0.6345,
        scale: 0.28,
        rotationDegrees: 77.5548
      },
      {
        symbolId: "cloud",
        x: 0.7968,
        y: 0.5176,
        scale: 0.3,
        rotationDegrees: 256.4531
      },
      {
        symbolId: "snowflake",
        x: 0.2338,
        y: 0.3939,
        scale: 0.26,
        rotationDegrees: 189.2024
      },
      {
        symbolId: "mushroom",
        x: 0.741,
        y: 0.7853,
        scale: 0.19,
        rotationDegrees: 348.9373
      },
      {
        symbolId: "rocket",
        x: 0.7137,
        y: 0.2078,
        scale: 0.21,
        rotationDegrees: 115.2672
      },
      {
        symbolId: "balloon",
        x: 0.2169,
        y: 0.6988,
        scale: 0.22,
        rotationDegrees: 261.7171
      },
      {
        symbolId: "test-tube",
        x: 0.4133,
        y: 0.8743,
        scale: 0.18,
        rotationDegrees: 133.8777
      },
      {
        symbolId: "eye",
        x: 0.4391,
        y: 0.1778,
        scale: 0.24,
        rotationDegrees: 103.2706
      }
    ]
  },
  {
    cardId: 41,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.7959,
        y: 0.4156,
        scale: 0.24,
        rotationDegrees: 304.0898
      },
      {
        symbolId: "lightning-bolt",
        x: 0.248,
        y: 0.4835,
        scale: 0.3,
        rotationDegrees: 331.3012
      },
      {
        symbolId: "cat",
        x: 0.6949,
        y: 0.1917,
        scale: 0.21,
        rotationDegrees: 242.4628
      },
      {
        symbolId: "frog",
        x: 0.5012,
        y: 0.5358,
        scale: 0.18,
        rotationDegrees: 102.1417
      },
      {
        symbolId: "sailboat",
        x: 0.4886,
        y: 0.3134,
        scale: 0.22,
        rotationDegrees: 63.4179
      },
      {
        symbolId: "planet",
        x: 0.285,
        y: 0.1992,
        scale: 0.19,
        rotationDegrees: 201.1511
      },
      {
        symbolId: "wand",
        x: 0.6912,
        y: 0.6978,
        scale: 0.28,
        rotationDegrees: 268.0809
      },
      {
        symbolId: "eye",
        x: 0.4161,
        y: 0.8081,
        scale: 0.26,
        rotationDegrees: 211.5224
      }
    ]
  },
  {
    cardId: 42,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.3585,
        y: 0.1671,
        scale: 0.22,
        rotationDegrees: 72.1011
      },
      {
        symbolId: "leaf",
        x: 0.5053,
        y: 0.3891,
        scale: 0.26,
        rotationDegrees: 237.6282
      },
      {
        symbolId: "turtle",
        x: 0.6555,
        y: 0.7519,
        scale: 0.28,
        rotationDegrees: 225.3275
      },
      {
        symbolId: "cherries",
        x: 0.7739,
        y: 0.4979,
        scale: 0.24,
        rotationDegrees: 104.9829
      },
      {
        symbolId: "lemon",
        x: 0.7518,
        y: 0.2508,
        scale: 0.19,
        rotationDegrees: 256.7433
      },
      {
        symbolId: "balloon",
        x: 0.3557,
        y: 0.8118,
        scale: 0.21,
        rotationDegrees: 274.0327
      },
      {
        symbolId: "wand",
        x: 0.1874,
        y: 0.546,
        scale: 0.3,
        rotationDegrees: 4.1107
      },
      {
        symbolId: "music-note",
        x: 0.5795,
        y: 0.1422,
        scale: 0.18,
        rotationDegrees: 359.9976
      }
    ]
  },
  {
    cardId: 43,
    printedSymbols: [
      {
        symbolId: "key",
        x: 0.4505,
        y: 0.8555,
        scale: 0.21,
        rotationDegrees: 312.4307
      },
      {
        symbolId: "camera",
        x: 0.8623,
        y: 0.4756,
        scale: 0.22,
        rotationDegrees: 302.6263
      },
      {
        symbolId: "butterfly",
        x: 0.2704,
        y: 0.6439,
        scale: 0.3,
        rotationDegrees: 95.7257
      },
      {
        symbolId: "watermelon",
        x: 0.6717,
        y: 0.7055,
        scale: 0.28,
        rotationDegrees: 187.3386
      },
      {
        symbolId: "rocket",
        x: 0.6404,
        y: 0.2359,
        scale: 0.24,
        rotationDegrees: 193.1051
      },
      {
        symbolId: "planet",
        x: 0.5492,
        y: 0.4528,
        scale: 0.19,
        rotationDegrees: 150.3028
      },
      {
        symbolId: "money-bag",
        x: 0.1286,
        y: 0.4274,
        scale: 0.18,
        rotationDegrees: 159.7237
      },
      {
        symbolId: "music-note",
        x: 0.3414,
        y: 0.3197,
        scale: 0.26,
        rotationDegrees: 6.2198
      }
    ]
  },
  {
    cardId: 44,
    printedSymbols: [
      {
        symbolId: "anchor",
        x: 0.7138,
        y: 0.7532,
        scale: 0.22,
        rotationDegrees: 155.5698
      },
      {
        symbolId: "sun",
        x: 0.4846,
        y: 0.4884,
        scale: 0.21,
        rotationDegrees: 105.2581
      },
      {
        symbolId: "cactus",
        x: 0.1628,
        y: 0.6698,
        scale: 0.19,
        rotationDegrees: 165.183
      },
      {
        symbolId: "mushroom",
        x: 0.7637,
        y: 0.4636,
        scale: 0.28,
        rotationDegrees: 257.1924
      },
      {
        symbolId: "sailboat",
        x: 0.7362,
        y: 0.203,
        scale: 0.18,
        rotationDegrees: 230.5096
      },
      {
        symbolId: "flying-saucer",
        x: 0.4189,
        y: 0.7534,
        scale: 0.26,
        rotationDegrees: 270.3539
      },
      {
        symbolId: "ghost",
        x: 0.2207,
        y: 0.4123,
        scale: 0.3,
        rotationDegrees: 286.6511
      },
      {
        symbolId: "music-note",
        x: 0.5002,
        y: 0.2336,
        scale: 0.24,
        rotationDegrees: 140.1207
      }
    ]
  },
  {
    cardId: 45,
    printedSymbols: [
      {
        symbolId: "wrench",
        x: 0.8575,
        y: 0.569,
        scale: 0.21,
        rotationDegrees: 148.1111
      },
      {
        symbolId: "moon",
        x: 0.6473,
        y: 0.793,
        scale: 0.28,
        rotationDegrees: 119.4381
      },
      {
        symbolId: "snowflake",
        x: 0.7719,
        y: 0.3003,
        scale: 0.26,
        rotationDegrees: 24.655
      },
      {
        symbolId: "frog",
        x: 0.2518,
        y: 0.2189,
        scale: 0.19,
        rotationDegrees: 97.6814
      },
      {
        symbolId: "bicycle",
        x: 0.5557,
        y: 0.5449,
        scale: 0.18,
        rotationDegrees: 62.7636
      },
      {
        symbolId: "crown",
        x: 0.2563,
        y: 0.6943,
        scale: 0.3,
        rotationDegrees: 24.6701
      },
      {
        symbolId: "dice",
        x: 0.4891,
        y: 0.2991,
        scale: 0.24,
        rotationDegrees: 131.2831
      },
      {
        symbolId: "music-note",
        x: 0.1495,
        y: 0.4326,
        scale: 0.22,
        rotationDegrees: 151.1677
      }
    ]
  },
  {
    cardId: 46,
    printedSymbols: [
      {
        symbolId: "magnet",
        x: 0.6844,
        y: 0.1808,
        scale: 0.19,
        rotationDegrees: 318.2108
      },
      {
        symbolId: "cloud",
        x: 0.6252,
        y: 0.7379,
        scale: 0.3,
        rotationDegrees: 50.4519
      },
      {
        symbolId: "cat",
        x: 0.175,
        y: 0.2955,
        scale: 0.18,
        rotationDegrees: 290.9077
      },
      {
        symbolId: "snail",
        x: 0.8032,
        y: 0.4219,
        scale: 0.24,
        rotationDegrees: 300.289
      },
      {
        symbolId: "cupcake",
        x: 0.5356,
        y: 0.4649,
        scale: 0.22,
        rotationDegrees: 302.3154
      },
      {
        symbolId: "shield",
        x: 0.3076,
        y: 0.813,
        scale: 0.21,
        rotationDegrees: 201.3527
      },
      {
        symbolId: "puzzle-piece",
        x: 0.4278,
        y: 0.2125,
        scale: 0.28,
        rotationDegrees: 341.7432
      },
      {
        symbolId: "music-note",
        x: 0.1851,
        y: 0.5559,
        scale: 0.26,
        rotationDegrees: 27.7479
      }
    ]
  },
  {
    cardId: 47,
    printedSymbols: [
      {
        symbolId: "bell",
        x: 0.5284,
        y: 0.65,
        scale: 0.26,
        rotationDegrees: 106.0916
      },
      {
        symbolId: "lightning-bolt",
        x: 0.8199,
        y: 0.6692,
        scale: 0.21,
        rotationDegrees: 104.5137
      },
      {
        symbolId: "whale",
        x: 0.3693,
        y: 0.8563,
        scale: 0.18,
        rotationDegrees: 158.6959
      },
      {
        symbolId: "bee",
        x: 0.7737,
        y: 0.336,
        scale: 0.3,
        rotationDegrees: 351.1122
      },
      {
        symbolId: "pretzel",
        x: 0.4731,
        y: 0.3681,
        scale: 0.24,
        rotationDegrees: 64.8624
      },
      {
        symbolId: "airplane",
        x: 0.5503,
        y: 0.1295,
        scale: 0.19,
        rotationDegrees: 242.8327
      },
      {
        symbolId: "star",
        x: 0.2128,
        y: 0.5663,
        scale: 0.28,
        rotationDegrees: 59.7082
      },
      {
        symbolId: "music-note",
        x: 0.2169,
        y: 0.2808,
        scale: 0.22,
        rotationDegrees: 254.2969
      }
    ]
  },
  {
    cardId: 48,
    printedSymbols: [
      {
        symbolId: "lock",
        x: 0.5838,
        y: 0.6101,
        scale: 0.3,
        rotationDegrees: 158.9848
      },
      {
        symbolId: "flame",
        x: 0.5014,
        y: 0.8718,
        scale: 0.19,
        rotationDegrees: 297.7627
      },
      {
        symbolId: "owl",
        x: 0.8553,
        y: 0.4634,
        scale: 0.21,
        rotationDegrees: 340.1321
      },
      {
        symbolId: "apple",
        x: 0.188,
        y: 0.525,
        scale: 0.26,
        rotationDegrees: 206.6794
      },
      {
        symbolId: "carrot",
        x: 0.826,
        y: 0.701,
        scale: 0.18,
        rotationDegrees: 169.0762
      },
      {
        symbolId: "train",
        x: 0.6505,
        y: 0.273,
        scale: 0.28,
        rotationDegrees: 185.2489
      },
      {
        symbolId: "test-tube",
        x: 0.3718,
        y: 0.2061,
        scale: 0.24,
        rotationDegrees: 208.043
      },
      {
        symbolId: "music-note",
        x: 0.2787,
        y: 0.7675,
        scale: 0.22,
        rotationDegrees: 224.3919
      }
    ]
  },
  {
    cardId: 49,
    printedSymbols: [
      {
        symbolId: "hammer",
        x: 0.5733,
        y: 0.1273,
        scale: 0.18,
        rotationDegrees: 342.0269
      },
      {
        symbolId: "key",
        x: 0.4252,
        y: 0.5615,
        scale: 0.19,
        rotationDegrees: 32.3045
      },
      {
        symbolId: "anchor",
        x: 0.3585,
        y: 0.1649,
        scale: 0.22,
        rotationDegrees: 202.9294
      },
      {
        symbolId: "wrench",
        x: 0.1915,
        y: 0.4103,
        scale: 0.3,
        rotationDegrees: 35.0998
      },
      {
        symbolId: "magnet",
        x: 0.7492,
        y: 0.6983,
        scale: 0.24,
        rotationDegrees: 178.728
      },
      {
        symbolId: "bell",
        x: 0.4287,
        y: 0.82,
        scale: 0.28,
        rotationDegrees: 30.3195
      },
      {
        symbolId: "lock",
        x: 0.8635,
        y: 0.4633,
        scale: 0.21,
        rotationDegrees: 104.5824
      },
      {
        symbolId: "boot",
        x: 0.6182,
        y: 0.3962,
        scale: 0.26,
        rotationDegrees: 200.5003
      }
    ]
  },
  {
    cardId: 50,
    printedSymbols: [
      {
        symbolId: "camera",
        x: 0.3091,
        y: 0.1738,
        scale: 0.18,
        rotationDegrees: 355.141
      },
      {
        symbolId: "sun",
        x: 0.6861,
        y: 0.7451,
        scale: 0.22,
        rotationDegrees: 321.1439
      },
      {
        symbolId: "moon",
        x: 0.8392,
        y: 0.5305,
        scale: 0.24,
        rotationDegrees: 334.8833
      },
      {
        symbolId: "cloud",
        x: 0.438,
        y: 0.6429,
        scale: 0.28,
        rotationDegrees: 311.5633
      },
      {
        symbolId: "lightning-bolt",
        x: 0.7891,
        y: 0.2724,
        scale: 0.19,
        rotationDegrees: 241.64
      },
      {
        symbolId: "flame",
        x: 0.1884,
        y: 0.4051,
        scale: 0.26,
        rotationDegrees: 350.2703
      },
      {
        symbolId: "leaf",
        x: 0.1763,
        y: 0.6738,
        scale: 0.21,
        rotationDegrees: 5.4307
      },
      {
        symbolId: "boot",
        x: 0.5268,
        y: 0.3146,
        scale: 0.3,
        rotationDegrees: 111.044
      }
    ]
  },
  {
    cardId: 51,
    printedSymbols: [
      {
        symbolId: "cactus",
        x: 0.1655,
        y: 0.4723,
        scale: 0.24,
        rotationDegrees: 136.9531
      },
      {
        symbolId: "snowflake",
        x: 0.2777,
        y: 0.2044,
        scale: 0.19,
        rotationDegrees: 209.9249
      },
      {
        symbolId: "cat",
        x: 0.3379,
        y: 0.8022,
        scale: 0.22,
        rotationDegrees: 258.2888
      },
      {
        symbolId: "whale",
        x: 0.6176,
        y: 0.759,
        scale: 0.18,
        rotationDegrees: 263.669
      },
      {
        symbolId: "owl",
        x: 0.5342,
        y: 0.2483,
        scale: 0.26,
        rotationDegrees: 342.4927
      },
      {
        symbolId: "turtle",
        x: 0.8101,
        y: 0.57,
        scale: 0.28,
        rotationDegrees: 34.2147
      },
      {
        symbolId: "butterfly",
        x: 0.7938,
        y: 0.2857,
        scale: 0.21,
        rotationDegrees: 74.8577
      },
      {
        symbolId: "boot",
        x: 0.4514,
        y: 0.538,
        scale: 0.3,
        rotationDegrees: 29.1361
      }
    ]
  },
  {
    cardId: 52,
    printedSymbols: [
      {
        symbolId: "frog",
        x: 0.8584,
        y: 0.3789,
        scale: 0.18,
        rotationDegrees: 120.3114
      },
      {
        symbolId: "snail",
        x: 0.3617,
        y: 0.2392,
        scale: 0.3,
        rotationDegrees: 124.9137
      },
      {
        symbolId: "bee",
        x: 0.7987,
        y: 0.6336,
        scale: 0.26,
        rotationDegrees: 162.5775
      },
      {
        symbolId: "apple",
        x: 0.2161,
        y: 0.4671,
        scale: 0.19,
        rotationDegrees: 122.5658
      },
      {
        symbolId: "cherries",
        x: 0.2672,
        y: 0.7227,
        scale: 0.28,
        rotationDegrees: 323.3835
      },
      {
        symbolId: "watermelon",
        x: 0.547,
        y: 0.8386,
        scale: 0.24,
        rotationDegrees: 14.6848
      },
      {
        symbolId: "mushroom",
        x: 0.6543,
        y: 0.2929,
        scale: 0.22,
        rotationDegrees: 171.9627
      },
      {
        symbolId: "boot",
        x: 0.516,
        y: 0.5366,
        scale: 0.21,
        rotationDegrees: 44.0213
      }
    ]
  },
  {
    cardId: 53,
    printedSymbols: [
      {
        symbolId: "cupcake",
        x: 0.4295,
        y: 0.1717,
        scale: 0.19,
        rotationDegrees: 93.0477
      },
      {
        symbolId: "pretzel",
        x: 0.3026,
        y: 0.6797,
        scale: 0.26,
        rotationDegrees: 40.1586
      },
      {
        symbolId: "carrot",
        x: 0.7857,
        y: 0.6728,
        scale: 0.28,
        rotationDegrees: 22.9763
      },
      {
        symbolId: "lemon",
        x: 0.6547,
        y: 0.1799,
        scale: 0.18,
        rotationDegrees: 305.3329
      },
      {
        symbolId: "rocket",
        x: 0.8171,
        y: 0.3362,
        scale: 0.22,
        rotationDegrees: 140.4618
      },
      {
        symbolId: "sailboat",
        x: 0.5078,
        y: 0.3946,
        scale: 0.24,
        rotationDegrees: 318.2477
      },
      {
        symbolId: "bicycle",
        x: 0.2084,
        y: 0.394,
        scale: 0.3,
        rotationDegrees: 83.0865
      },
      {
        symbolId: "boot",
        x: 0.5521,
        y: 0.7955,
        scale: 0.21,
        rotationDegrees: 63.6507
      }
    ]
  },
  {
    cardId: 54,
    printedSymbols: [
      {
        symbolId: "airplane",
        x: 0.2364,
        y: 0.3322,
        scale: 0.28,
        rotationDegrees: 216.6584
      },
      {
        symbolId: "train",
        x: 0.3019,
        y: 0.8183,
        scale: 0.18,
        rotationDegrees: 142.1394
      },
      {
        symbolId: "balloon",
        x: 0.6325,
        y: 0.208,
        scale: 0.3,
        rotationDegrees: 330.0298
      },
      {
        symbolId: "planet",
        x: 0.8061,
        y: 0.7105,
        scale: 0.19,
        rotationDegrees: 252.8403
      },
      {
        symbolId: "flying-saucer",
        x: 0.7845,
        y: 0.4712,
        scale: 0.24,
        rotationDegrees: 91.6273
      },
      {
        symbolId: "crown",
        x: 0.5536,
        y: 0.8423,
        scale: 0.21,
        rotationDegrees: 353.7776
      },
      {
        symbolId: "shield",
        x: 0.4549,
        y: 0.6038,
        scale: 0.26,
        rotationDegrees: 345.1134
      },
      {
        symbolId: "boot",
        x: 0.1928,
        y: 0.6276,
        scale: 0.22,
        rotationDegrees: 38.3583
      }
    ]
  },
  {
    cardId: 55,
    printedSymbols: [
      {
        symbolId: "test-tube",
        x: 0.763,
        y: 0.6898,
        scale: 0.26,
        rotationDegrees: 152.1676
      },
      {
        symbolId: "wand",
        x: 0.1493,
        y: 0.6534,
        scale: 0.18,
        rotationDegrees: 42.9257
      },
      {
        symbolId: "money-bag",
        x: 0.297,
        y: 0.4306,
        scale: 0.3,
        rotationDegrees: 22.7966
      },
      {
        symbolId: "ghost",
        x: 0.3485,
        y: 0.1609,
        scale: 0.19,
        rotationDegrees: 315.9413
      },
      {
        symbolId: "dice",
        x: 0.8429,
        y: 0.3741,
        scale: 0.21,
        rotationDegrees: 61.5048
      },
      {
        symbolId: "puzzle-piece",
        x: 0.6117,
        y: 0.1695,
        scale: 0.24,
        rotationDegrees: 39.2548
      },
      {
        symbolId: "star",
        x: 0.6159,
        y: 0.4698,
        scale: 0.22,
        rotationDegrees: 278.4017
      },
      {
        symbolId: "boot",
        x: 0.3756,
        y: 0.7564,
        scale: 0.28,
        rotationDegrees: 240.8222
      }
    ]
  },
  {
    cardId: 56,
    printedSymbols: [
      {
        symbolId: "heart",
        x: 0.4455,
        y: 0.4019,
        scale: 0.3,
        rotationDegrees: 327.8128
      },
      {
        symbolId: "diamond",
        x: 0.8284,
        y: 0.4629,
        scale: 0.28,
        rotationDegrees: 356.6617
      },
      {
        symbolId: "cyclone",
        x: 0.2785,
        y: 0.1919,
        scale: 0.19,
        rotationDegrees: 124.5939
      },
      {
        symbolId: "water-drop",
        x: 0.7785,
        y: 0.7553,
        scale: 0.18,
        rotationDegrees: 276.7108
      },
      {
        symbolId: "four-leaf-clover",
        x: 0.2608,
        y: 0.7585,
        scale: 0.24,
        rotationDegrees: 106.7394
      },
      {
        symbolId: "eye",
        x: 0.6458,
        y: 0.1758,
        scale: 0.22,
        rotationDegrees: 306.1042
      },
      {
        symbolId: "music-note",
        x: 0.5443,
        y: 0.8254,
        scale: 0.26,
        rotationDegrees: 141.9087
      },
      {
        symbolId: "boot",
        x: 0.1587,
        y: 0.5196,
        scale: 0.21,
        rotationDegrees: 55.8313
      }
    ]
  }
] as const satisfies SymbolMatchPrintedLayouts;
