import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createSymbolMatchArtifactFingerprint } from "./fingerprint.js";
import {
  generateSymbolMatchDeck,
  SYMBOL_MATCH_DECK_GENERATOR_VERSION
} from "./generateDeck.js";
import {
  generateSymbolMatchPrintedLayouts,
  SYMBOL_MATCH_LAYOUT_GENERATOR_VERSION
} from "./generatePrintedLayouts.js";

function serializeArtifact(input: {
  typeName: string;
  dataName: string;
  data: unknown;
  fingerprintName: string;
  fingerprint: string;
  versionName: string;
  version: string;
}): string {
  return `// This file is generated by generateArtifacts.ts. Do not edit it manually.
import type { ${input.typeName} } from "./types.js";

export const ${input.versionName} = ${JSON.stringify(input.version)};
export const ${input.fingerprintName} = ${JSON.stringify(input.fingerprint)};

export const ${input.dataName} = ${JSON.stringify(input.data, null, 2)} as const satisfies ${input.typeName};
`;
}

async function generateArtifacts(): Promise<void> {
  const artifactSourceDirectory = resolve(
    process.cwd(),
    "src/game/symbol-match/artifacts"
  );
  const deck = generateSymbolMatchDeck();
  const layouts = generateSymbolMatchPrintedLayouts(deck);
  const deckSource = serializeArtifact({
    typeName: "SymbolMatchDeck",
    dataName: "SYMBOL_MATCH_DECK",
    data: deck,
    fingerprintName: "SYMBOL_MATCH_DECK_FINGERPRINT",
    fingerprint: createSymbolMatchArtifactFingerprint(deck),
    versionName: "SYMBOL_MATCH_DECK_VERSION",
    version: SYMBOL_MATCH_DECK_GENERATOR_VERSION
  });
  const layoutsSource = serializeArtifact({
    typeName: "SymbolMatchPrintedLayouts",
    dataName: "SYMBOL_MATCH_PRINTED_LAYOUTS",
    data: layouts,
    fingerprintName: "SYMBOL_MATCH_PRINTED_LAYOUTS_FINGERPRINT",
    fingerprint: createSymbolMatchArtifactFingerprint(layouts),
    versionName: "SYMBOL_MATCH_PRINTED_LAYOUTS_VERSION",
    version: SYMBOL_MATCH_LAYOUT_GENERATOR_VERSION
  });

  await Promise.all([
    writeFile(
      resolve(artifactSourceDirectory, "generatedDeck.ts"),
      deckSource,
      "utf8"
    ),
    writeFile(
      resolve(artifactSourceDirectory, "generatedPrintedLayouts.ts"),
      layoutsSource,
      "utf8"
    )
  ]);
}

await generateArtifacts();
