// This file is generated by generateArtifacts.ts. Do not edit it manually.
import type { SymbolMatchDeck } from "./types.js";

export const SYMBOL_MATCH_DECK_VERSION = "projective-plane-order-7-v1";
export const SYMBOL_MATCH_DECK_FINGERPRINT =
  "sha256:b96caa522ecf2a9043bf6b822f026dbf099fd612730094e58b9bc5258dc289c4";

export const SYMBOL_MATCH_DECK = [
  {
    id: 0,
    symbolIds: [
      "hammer",
      "camera",
      "cactus",
      "frog",
      "cupcake",
      "airplane",
      "potion",
      "heart"
    ]
  },
  {
    id: 1,
    symbolIds: [
      "key",
      "sun",
      "snowflake",
      "snail",
      "pretzel",
      "train",
      "wand",
      "heart"
    ]
  },
  {
    id: 2,
    symbolIds: [
      "anchor",
      "moon",
      "cat",
      "bee",
      "carrot",
      "balloon",
      "treasure-chest",
      "heart"
    ]
  },
  {
    id: 3,
    symbolIds: [
      "wrench",
      "cloud",
      "whale",
      "apple",
      "lemon",
      "planet",
      "ghost",
      "heart"
    ]
  },
  {
    id: 4,
    symbolIds: [
      "magnet",
      "lightning-bolt",
      "owl",
      "cherries",
      "rocket",
      "flying-saucer",
      "dice",
      "heart"
    ]
  },
  {
    id: 5,
    symbolIds: [
      "bell",
      "flame",
      "turtle",
      "watermelon",
      "sailboat",
      "crown",
      "puzzle-piece",
      "heart"
    ]
  },
  {
    id: 6,
    symbolIds: [
      "lock",
      "leaf",
      "butterfly",
      "mushroom",
      "bicycle",
      "shield",
      "star",
      "heart"
    ]
  },
  {
    id: 7,
    symbolIds: [
      "hammer",
      "sun",
      "cat",
      "apple",
      "rocket",
      "crown",
      "star",
      "diamond"
    ]
  },
  {
    id: 8,
    symbolIds: [
      "key",
      "moon",
      "whale",
      "cherries",
      "sailboat",
      "shield",
      "potion",
      "diamond"
    ]
  },
  {
    id: 9,
    symbolIds: [
      "anchor",
      "cloud",
      "owl",
      "watermelon",
      "bicycle",
      "airplane",
      "wand",
      "diamond"
    ]
  },
  {
    id: 10,
    symbolIds: [
      "wrench",
      "lightning-bolt",
      "turtle",
      "mushroom",
      "cupcake",
      "train",
      "treasure-chest",
      "diamond"
    ]
  },
  {
    id: 11,
    symbolIds: [
      "magnet",
      "flame",
      "butterfly",
      "frog",
      "pretzel",
      "balloon",
      "ghost",
      "diamond"
    ]
  },
  {
    id: 12,
    symbolIds: [
      "bell",
      "leaf",
      "cactus",
      "snail",
      "carrot",
      "planet",
      "dice",
      "diamond"
    ]
  },
  {
    id: 13,
    symbolIds: [
      "lock",
      "camera",
      "snowflake",
      "bee",
      "lemon",
      "flying-saucer",
      "puzzle-piece",
      "diamond"
    ]
  },
  {
    id: 14,
    symbolIds: [
      "hammer",
      "moon",
      "owl",
      "mushroom",
      "pretzel",
      "planet",
      "puzzle-piece",
      "spiral"
    ]
  },
  {
    id: 15,
    symbolIds: [
      "key",
      "cloud",
      "turtle",
      "frog",
      "carrot",
      "flying-saucer",
      "star",
      "spiral"
    ]
  },
  {
    id: 16,
    symbolIds: [
      "anchor",
      "lightning-bolt",
      "butterfly",
      "snail",
      "lemon",
      "crown",
      "potion",
      "spiral"
    ]
  },
  {
    id: 17,
    symbolIds: [
      "wrench",
      "flame",
      "cactus",
      "bee",
      "rocket",
      "shield",
      "wand",
      "spiral"
    ]
  },
  {
    id: 18,
    symbolIds: [
      "magnet",
      "leaf",
      "snowflake",
      "apple",
      "sailboat",
      "airplane",
      "treasure-chest",
      "spiral"
    ]
  },
  {
    id: 19,
    symbolIds: [
      "bell",
      "camera",
      "cat",
      "cherries",
      "bicycle",
      "train",
      "ghost",
      "spiral"
    ]
  },
  {
    id: 20,
    symbolIds: [
      "lock",
      "sun",
      "whale",
      "watermelon",
      "cupcake",
      "balloon",
      "dice",
      "spiral"
    ]
  },
  {
    id: 21,
    symbolIds: [
      "hammer",
      "cloud",
      "butterfly",
      "bee",
      "sailboat",
      "train",
      "dice",
      "water-drop"
    ]
  },
  {
    id: 22,
    symbolIds: [
      "key",
      "lightning-bolt",
      "cactus",
      "apple",
      "bicycle",
      "balloon",
      "puzzle-piece",
      "water-drop"
    ]
  },
  {
    id: 23,
    symbolIds: [
      "anchor",
      "flame",
      "snowflake",
      "cherries",
      "cupcake",
      "planet",
      "star",
      "water-drop"
    ]
  },
  {
    id: 24,
    symbolIds: [
      "wrench",
      "leaf",
      "cat",
      "watermelon",
      "pretzel",
      "flying-saucer",
      "potion",
      "water-drop"
    ]
  },
  {
    id: 25,
    symbolIds: [
      "magnet",
      "camera",
      "whale",
      "mushroom",
      "carrot",
      "crown",
      "wand",
      "water-drop"
    ]
  },
  {
    id: 26,
    symbolIds: [
      "bell",
      "sun",
      "owl",
      "frog",
      "lemon",
      "shield",
      "treasure-chest",
      "water-drop"
    ]
  },
  {
    id: 27,
    symbolIds: [
      "lock",
      "moon",
      "turtle",
      "snail",
      "rocket",
      "airplane",
      "ghost",
      "water-drop"
    ]
  },
  {
    id: 28,
    symbolIds: [
      "hammer",
      "lightning-bolt",
      "snowflake",
      "watermelon",
      "carrot",
      "shield",
      "ghost",
      "four-leaf-clover"
    ]
  },
  {
    id: 29,
    symbolIds: [
      "key",
      "flame",
      "cat",
      "mushroom",
      "lemon",
      "airplane",
      "dice",
      "four-leaf-clover"
    ]
  },
  {
    id: 30,
    symbolIds: [
      "anchor",
      "leaf",
      "whale",
      "frog",
      "rocket",
      "train",
      "puzzle-piece",
      "four-leaf-clover"
    ]
  },
  {
    id: 31,
    symbolIds: [
      "wrench",
      "camera",
      "owl",
      "snail",
      "sailboat",
      "balloon",
      "star",
      "four-leaf-clover"
    ]
  },
  {
    id: 32,
    symbolIds: [
      "magnet",
      "sun",
      "turtle",
      "bee",
      "bicycle",
      "planet",
      "potion",
      "four-leaf-clover"
    ]
  },
  {
    id: 33,
    symbolIds: [
      "bell",
      "moon",
      "butterfly",
      "apple",
      "cupcake",
      "flying-saucer",
      "wand",
      "four-leaf-clover"
    ]
  },
  {
    id: 34,
    symbolIds: [
      "lock",
      "cloud",
      "cactus",
      "cherries",
      "pretzel",
      "crown",
      "treasure-chest",
      "four-leaf-clover"
    ]
  },
  {
    id: 35,
    symbolIds: [
      "hammer",
      "flame",
      "whale",
      "snail",
      "bicycle",
      "flying-saucer",
      "treasure-chest",
      "eye"
    ]
  },
  {
    id: 36,
    symbolIds: ["key", "leaf", "owl", "bee", "cupcake", "crown", "ghost", "eye"]
  },
  {
    id: 37,
    symbolIds: [
      "anchor",
      "camera",
      "turtle",
      "apple",
      "pretzel",
      "shield",
      "dice",
      "eye"
    ]
  },
  {
    id: 38,
    symbolIds: [
      "wrench",
      "sun",
      "butterfly",
      "cherries",
      "carrot",
      "airplane",
      "puzzle-piece",
      "eye"
    ]
  },
  {
    id: 39,
    symbolIds: [
      "magnet",
      "moon",
      "cactus",
      "watermelon",
      "lemon",
      "train",
      "star",
      "eye"
    ]
  },
  {
    id: 40,
    symbolIds: [
      "bell",
      "cloud",
      "snowflake",
      "mushroom",
      "rocket",
      "balloon",
      "potion",
      "eye"
    ]
  },
  {
    id: 41,
    symbolIds: [
      "lock",
      "lightning-bolt",
      "cat",
      "frog",
      "sailboat",
      "planet",
      "wand",
      "eye"
    ]
  },
  {
    id: 42,
    symbolIds: [
      "hammer",
      "leaf",
      "turtle",
      "cherries",
      "lemon",
      "balloon",
      "wand",
      "music-note"
    ]
  },
  {
    id: 43,
    symbolIds: [
      "key",
      "camera",
      "butterfly",
      "watermelon",
      "rocket",
      "planet",
      "treasure-chest",
      "music-note"
    ]
  },
  {
    id: 44,
    symbolIds: [
      "anchor",
      "sun",
      "cactus",
      "mushroom",
      "sailboat",
      "flying-saucer",
      "ghost",
      "music-note"
    ]
  },
  {
    id: 45,
    symbolIds: [
      "wrench",
      "moon",
      "snowflake",
      "frog",
      "bicycle",
      "crown",
      "dice",
      "music-note"
    ]
  },
  {
    id: 46,
    symbolIds: [
      "magnet",
      "cloud",
      "cat",
      "snail",
      "cupcake",
      "shield",
      "puzzle-piece",
      "music-note"
    ]
  },
  {
    id: 47,
    symbolIds: [
      "bell",
      "lightning-bolt",
      "whale",
      "bee",
      "pretzel",
      "airplane",
      "star",
      "music-note"
    ]
  },
  {
    id: 48,
    symbolIds: [
      "lock",
      "flame",
      "owl",
      "apple",
      "carrot",
      "train",
      "potion",
      "music-note"
    ]
  },
  {
    id: 49,
    symbolIds: [
      "hammer",
      "key",
      "anchor",
      "wrench",
      "magnet",
      "bell",
      "lock",
      "boot"
    ]
  },
  {
    id: 50,
    symbolIds: [
      "camera",
      "sun",
      "moon",
      "cloud",
      "lightning-bolt",
      "flame",
      "leaf",
      "boot"
    ]
  },
  {
    id: 51,
    symbolIds: [
      "cactus",
      "snowflake",
      "cat",
      "whale",
      "owl",
      "turtle",
      "butterfly",
      "boot"
    ]
  },
  {
    id: 52,
    symbolIds: [
      "frog",
      "snail",
      "bee",
      "apple",
      "cherries",
      "watermelon",
      "mushroom",
      "boot"
    ]
  },
  {
    id: 53,
    symbolIds: [
      "cupcake",
      "pretzel",
      "carrot",
      "lemon",
      "rocket",
      "sailboat",
      "bicycle",
      "boot"
    ]
  },
  {
    id: 54,
    symbolIds: [
      "airplane",
      "train",
      "balloon",
      "planet",
      "flying-saucer",
      "crown",
      "shield",
      "boot"
    ]
  },
  {
    id: 55,
    symbolIds: [
      "potion",
      "wand",
      "treasure-chest",
      "ghost",
      "dice",
      "puzzle-piece",
      "star",
      "boot"
    ]
  },
  {
    id: 56,
    symbolIds: [
      "heart",
      "diamond",
      "spiral",
      "water-drop",
      "four-leaf-clover",
      "eye",
      "music-note",
      "boot"
    ]
  }
] as const satisfies SymbolMatchDeck;
